GET http://localhost:5000/book

###
GET http://localhost:5000/book/6477860ae5fe4be278ab26e1

###
POST http://localhost:5000/book
Content-Type: application/json

{
   "kode": "B0002",
   "judul": "Makan Nasi Sisa",
   "pengarang": "Orang Susah",
   "penerbit" : "Semoga Terbit"
}

###
PATCH http://localhost:5000/book/6477860ae5fe4be278ab26e1
Content-Type: application/json

{
   "kode": "B0001",
   "judul": "Bisnis Harus Optimis",
   "pengarang": "Budi Harambe",
   "penerbit" : "Matahari Terbit"
}

###
DELETE http://localhost:5000/book/6477860ae5fe4be278ab26e1


###
GET http://localhost:5000/user

###
POST http://localhost:5000/user
Content-Type: application/json

{
   "kode": "U005",  
   "nama": "TES DELETE",
   "jenisKelamin": "perempuan",
   "contacts": {"email": "tes@gmail.com", "noHP": "1231231"},
   "roles": {"code" : 3, "desc": "User"} 
}

###
PATCH http://localhost:5000/user/6478d213eff8a2a4bbd6d541
Content-Type: application/json

{
   "kode": "U004",  
   "nama": "Ribi",
   "jenisKelamin": "perempuan",
   "contacts": {"email": "ribi@hotmail.com", "noHP": "0985546842"},
   "roles": {"code" : 3, "desc": "User"} 
}

###
GET http://localhost:5000/user/6478d5a25f5f22276d30e34b

###
DELETE http://localhost:5000/user/6478d5a25f5f22276d30e34b